name: Update Shortlinks

on:
  repository_dispatch:
    types: [update-links]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update links.json
        run: |
          echo '${{ github.event.client_payload.links }}' > links.json
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add links.json
          git commit -m "Update shortlinks"
          git push
